"""pop

Revision ID: 094d71d3cc6c
Revises: 0c1d9801e513
Create Date: 2023-06-12 08:27:37.013895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094d71d3cc6c'
down_revision = '0c1d9801e513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
